<a href="https://colab.research.google.com/github/Mosime2001/first-project-data-analysis-/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Debt Analysis Project**


Data Used Is From:
*   World Bank Datasets
*   Kaggle

The Project Structure is as follows:


1.   objectives
2.   Data Collection
3.   Dta Cleaning and Processing
4.   Exploratory Data Analysis
5.   Data Analysis
6.   Visualization Comparison
7.   Interpretation Of Results

**Libraries Import**

In [23]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib
import matplotlib.pyplot as plt

plt.style.use('ggplot')
from matplotlib.pyplot import figure

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

df = pd.read_excel("/P_Data.xlsx")
#df2 = pd.read_csv("/DEBT- of GDP.csv")
#df3 = pd.read_csv("/GDP.csv")

**Read Data File: External Debt Stocks**

In [25]:
df.head()

,Time,Time Code,Counterpart-Area Name,Counterpart-Area Code,Country Name,Country Code,"External debt stocks, long-term (DOD, current US$) [DT.DOD.DLXF.CD]"
0,2022,YR2022,Afghanistan,625,Afghanistan,AFG,..
1,2022,YR2022,Afghanistan,625,Albania,ALB,..
2,2022,YR2022,Afghanistan,625,Algeria,DZA,..
3,2022,YR2022,Afghanistan,625,Angola,AGO,..
4,2022,YR2022,Afghanistan,625,Argentina,ARG,..

In [28]:
df.dtypes

Time                                                                   object
Time Code                                                              object
Counterpart-Area Name                                                  object
Counterpart-Area Code                                                  object
Country Name                                                           object
Country Code                                                           object
External debt stocks, long-term (DOD, current US$) [DT.DOD.DLXF.CD]    object
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404685 entries, 0 to 404684
Data columns (total 7 columns):
 #   Column                                                               Non-Null Count   Dtype
---  ------                                                               --------------   -----
 0   Time                                                                 404682 non-null  object
 1   Time Code                                                            404680 non-null  object
 2   Counterpart-Area Name                                                404680 non-null  object
 3   Counterpart-Area Code                                                404680 non-null  object
 4   Country Name                                                         404680 non-null  object
 5   Country Code                                                         404680 non-null  object
 6   External debt stocks, long-term (DOD, current US$) [DT.DOD.DLXF.CD]  404680 non-null  object
dtypes: object(7)
memory usage: 21.6+ MB

In [30]:
df.describe()

,Time,Time Code,Counterpart-Area Name,Counterpart-Area Code,Country Name,Country Code,"External debt stocks, long-term (DOD, current US$) [DT.DOD.DLXF.CD]"
count,404682,404680,404680,404680,404680,404680,404680
unique,12,10,302,302,134,134,6696
top,2022,YR2022,Zimbabwe,265,Afghanistan,AFG,..
freq,40468,40468,1340,1340,3020,3020,396396

In [31]:
df.shape

(404685, 7)

**Read Data File: Debt Of GDP**

In [40]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib
import matplotlib.pyplot as plt

plt.style.use('ggplot')
from matplotlib.pyplot import figure

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

df2 = pd.read_csv("/DEBT- of GDP.csv")
#df3 = pd.read_csv("/GDP.csv")

In [36]:
df2.head()

,DEBT (% of GDP),1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.02,20.24,18.37,16.78,7.90,7.14,6.63,6.75,6.38,6.25
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.69,53.55,55.14,59.67,57.72,59.41,62.14,70.39,72.04,73.32
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.30,13.61,8.39,10.16,10.87,9.49,9.49,7.74,7.96,9.06
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.70,16.07,16.65,22.71,44.29,33.80,29.49,32.87,40.66,64.24
4,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.04,14.04,15.40,25.10,32.50,29.21,30.94,30.42,24.11,22.15

In [42]:
df2.dtypes

DEBT (% of GDP)     object
1800               float64
1801               float64
1802               float64
1803               float64
                    ...
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
Length: 217, dtype: object

In [43]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Columns: 217 entries, DEBT (% of GDP) to 2015
dtypes: float64(216), object(1)
memory usage: 329.0+ KB

In [44]:
df2.describe()

,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
count,4.000000,4.0000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,191.000000,190.000000,191.000000,191.000000,191.000000,190.000000,191.000000,191.000000,191.000000,191.000000
mean,81.677500,81.0075,85.507500,85.910000,85.067500,82.787500,82.487500,82.220000,81.607500,80.600000,...,51.438586,44.624474,44.610262,47.382304,46.722042,47.234105,48.195288,49.813822,51.681885,54.735131
std,72.091184,73.0218,78.402698,79.353498,78.292695,80.701447,83.788327,85.067491,83.930715,82.409149,...,45.302918,33.527042,37.746423,33.843059,31.601039,32.751866,33.417697,33.979342,33.743066,32.622709
min,18.080000,15.7200,16.470000,15.800000,16.180000,13.900000,12.430000,12.270000,14.140000,11.350000,...,0.980000,0.690000,0.470000,0.680000,0.630000,0.580000,0.550000,0.530000,0.070000,0.060000
25%,30.267500,29.6175,29.497500,29.405000,29.095000,23.492500,19.862500,17.812500,16.997500,19.255000,...,24.770000,22.060000,20.310000,24.730000,26.125000,26.340000,26.350000,28.190000,30.595000,33.765000
50%,65.895000,65.4200,68.285000,68.585000,67.845000,64.090000,62.440000,61.365000,60.390000,61.030000,...,39.600000,36.980000,36.750000,39.450000,40.630000,39.760000,39.790000,41.490000,44.390000,48.500000
75%,117.305000,116.8100,124.295000,125.090000,123.817500,123.385000,125.065000,125.772500,125.000000,122.375000,...,64.645000,62.020000,59.775000,62.785000,60.550000,64.797500,63.015000,67.345000,68.480000,70.905000
max,176.840000,177.4700,188.990000,190.670000,188.400000,189.070000,192.640000,193.880000,191.510000,188.990000,...,357.740000,183.010000,309.660000,210.250000,215.820000,231.630000,238.010000,244.480000,249.110000,247.980000

In [45]:
df2.shape

(194, 217)

**Read Data File: GDP**

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib
import matplotlib.pyplot as plt

plt.style.use('ggplot')
from matplotlib.pyplot import figure

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

df3 = pd.read_csv("/GDP.csv")

In [48]:
df3.head()

,Country,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.276188e+09,3.395794e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,2.112502e+10,2.161623e+10,2.350628e+10,2.804836e+10,2.592067e+10,2.947210e+10,3.201437e+10,3.326951e+10,...,9.859871e+11,1.006526e+12,9.273485e+11,8.851764e+11,1.021043e+12,1.007196e+12,1.000834e+12,9.275933e+11,1.081998e+12,1.169484e+12
2,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,2.056449e+10,2.055058e+10,1.999814e+10,1.801955e+10,1.889635e+10,1.841886e+10,1.890450e+10,2.014345e+10,1.458314e+10,NaN
3,Africa Western and Central,AFW,1.044764e+10,1.117321e+10,1.199053e+10,1.272769e+10,1.389811e+10,1.492979e+10,1.591084e+10,1.451058e+10,...,8.339481e+11,8.943225e+11,7.686447e+11,6.913634e+11,6.848988e+11,7.670257e+11,8.225384e+11,7.864600e+11,8.444597e+11,8.778633e+11
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.024137e+10,6.568544e+10,1.067136e+11

In [49]:
df3.dtypes

Country          object
Country Code     object
1960            float64
1961            float64
1962            float64
                 ...
2018            float64
2019            float64
2020            float64
2021            float64
2022            float64
Length: 65, dtype: object

In [50]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 65 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       266 non-null    object
 1   Country Code  266 non-null    object
 2   1960          132 non-null    float64
 3   1961          134 non-null    float64
 4   1962          136 non-null    float64
 5   1963          136 non-null    float64
 6   1964          136 non-null    float64
 7   1965          147 non-null    float64
 8   1966          150 non-null    float64
 9   1967          153 non-null    float64
 10  1968          158 non-null    float64
 11  1969          158 non-null    float64
 12  1970          167 non-null    float64
 13  1971          170 non-null    float64
 14  1972          170 non-null    float64
 15  1973          170 non-null    float64
 16  1974          171 non-null    float64
 17  1975          173 non-null    float64
 18  1976          174 non-null    float64
 19  1977          177 non-null    float64
 20  1978          176 non-null    float64
 21  1979          177 non-null    float64
 22  1980          191 non-null    float64
 23  1981          194 non-null    float64
 24  1982          195 non-null    float64
 25  1983          196 non-null    float64
 26  1984          197 non-null    float64
 27  1985          199 non-null    float64
 28  1986          201 non-null    float64
 29  1987          205 non-null    float64
 30  1988          210 non-null    float64
 31  1989          210 non-null    float64
 32  1990          226 non-null    float64
 33  1991          226 non-null    float64
 34  1992          227 non-null    float64
 35  1993          229 non-null    float64
 36  1994          231 non-null    float64
 37  1995          240 non-null    float64
 38  1996          240 non-null    float64
 39  1997          240 non-null    float64
 40  1998          242 non-null    float64
 41  1999          243 non-null    float64
 42  2000          247 non-null    float64
 43  2001          249 non-null    float64
 44  2002          254 non-null    float64
 45  2003          254 non-null    float64
 46  2004          254 non-null    float64
 47  2005          254 non-null    float64
 48  2006          255 non-null    float64
 49  2007          255 non-null    float64
 50  2008          256 non-null    float64
 51  2009          256 non-null    float64
 52  2010          257 non-null    float64
 53  2011          260 non-null    float64
 54  2012          258 non-null    float64
 55  2013          259 non-null    float64
 56  2014          260 non-null    float64
 57  2015          258 non-null    float64
 58  2016          258 non-null    float64
 59  2017          258 non-null    float64
 60  2018          258 non-null    float64
 61  2019          257 non-null    float64
 62  2020          257 non-null    float64
 63  2021          251 non-null    float64
 64  2022          233 non-null    float64
dtypes: float64(63), object(2)
memory usage: 135.2+ KB

In [51]:
df3.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
count,1.320000e+02,1.340000e+02,1.360000e+02,1.360000e+02,1.360000e+02,1.470000e+02,1.500000e+02,1.530000e+02,1.580000e+02,1.580000e+02,...,2.590000e+02,2.600000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.570000e+02,2.570000e+02,2.510000e+02,2.330000e+02
mean,7.127083e+10,7.274846e+10,7.639516e+10,8.236303e+10,9.048173e+10,9.182705e+10,1.021722e+11,1.059782e+11,1.111099e+11,1.228651e+11,...,2.478710e+12,2.540064e+12,2.401518e+12,2.435921e+12,2.611092e+12,2.773992e+12,2.826371e+12,2.739712e+12,3.211350e+12,3.599791e+12
std,2.135947e+11,2.223876e+11,2.370024e+11,2.549141e+11,2.788048e+11,2.927440e+11,3.205033e+11,3.389517e+11,3.608829e+11,3.971955e+11,...,8.393417e+12,8.604724e+12,8.165753e+12,8.306057e+12,8.840816e+12,9.410423e+12,9.564901e+12,9.318754e+12,1.072358e+13,1.147951e+13
min,1.201203e+07,1.159202e+07,9.122751e+06,1.084010e+07,1.271247e+07,1.359393e+07,1.446908e+07,1.583510e+07,1.460000e+07,1.585000e+07,...,3.861589e+07,3.876097e+07,3.681193e+07,4.162906e+07,4.527661e+07,4.801522e+07,5.412320e+07,5.174657e+07,6.019637e+07,6.034939e+07
25%,5.288385e+08,5.361919e+08,5.429342e+08,5.687581e+08,5.731182e+08,5.963705e+08,6.499792e+08,6.316797e+08,6.583150e+08,7.116598e+08,...,8.486163e+09,9.034786e+09,8.752203e+09,8.620796e+09,9.319389e+09,1.002804e+10,1.038167e+10,9.754600e+09,1.150202e+10,1.567158e+10
50%,3.040214e+09,2.965945e+09,3.049474e+09,3.569338e+09,3.432187e+09,3.120871e+09,3.549759e+09,3.384063e+09,3.950426e+09,4.526894e+09,...,5.094967e+10,5.339986e+10,4.966768e+10,4.980725e+10,5.400064e+10,5.614400e+10,6.028350e+10,5.370680e+10,6.568544e+10,8.227481e+10
75%,3.103045e+10,3.128542e+10,3.161860e+10,3.617095e+10,3.401420e+10,2.851910e+10,3.082854e+10,3.108639e+10,3.451917e+10,3.766365e+10,...,5.390198e+11,5.478564e+11,5.020845e+11,5.057567e+11,5.369244e+11,5.524163e+11,5.439767e+11,5.470542e+11,7.400410e+11,9.911146e+11
max,1.384857e+12,1.449221e+12,1.550815e+12,1.671447e+12,1.830492e+12,1.994103e+12,2.164118e+12,2.302577e+12,2.484674e+12,2.740499e+12,...,7.763515e+13,7.975652e+13,7.521506e+13,7.648645e+13,8.144205e+13,8.650222e+13,8.772810e+13,8.521515e+13,9.688240e+13,1.005620e+14

In [52]:
df3.shape

(266, 65)

## **Cleaning Data**

In [53]:
df[df.duplicated() == True]

,Time,Time Code,Counterpart-Area Name,Counterpart-Area Code,Country Name,Country Code,"External debt stocks, long-term (DOD, current US$) [DT.DOD.DLXF.CD]"
404681,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404682,NaN,NaN,NaN,NaN,NaN,NaN,NaN